spring:
  application:
    name: test
  rabbitmq:
    username: guest
    password: guest
    port: 5672
  cloud:
    stream:
      rabbit:
        bindings:
          event-input:
            consumer:
#              requeue-rejected: true
              auto-bind-dlq: true
              republish-to-dlq: true
              acknowledge-mode: MANUAL
              prefetch: 3

          aa-event:
            producer:
              exchangeType: direct
            consumer:
              exchangeType: direct
#      kafka:
#        binder:
#          brokers: 127.0.0.1:9092
#          zk-nodes: 127.0.0.1:2181
#          headers: eventType
      bindings:
        event-output:
          destination: service-event
#          content-type: application/json
        event-input:
          destination:  service-event
#          content-type: application/json
          group: ${spring.application.name}
          consumer:
            concurrency: 30
#            max-attempts: 4
        aa-event:
          destination:  service-event
          group: asdfa



#        event-bus-input-ext:
#          destination: institution-service-event
#          group: ${spring.application.name}
#          content-type: application/json


logging:
  level:
    org.springframework: info
    com.guns21: debug