spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: test
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    virtual-host: guns21.example
  cloud:
    stream:
      rabbit:
        bindings:
          event-output:
            producer:
#              spring.cloud.stream.rabbit.bindings.requestChannel.producer.routing-key-expression=payload.eventType
#              The problem is that the payload has already been serialized by the time the message reaches the channel adapter (where the routing key expression is evaluated).
#              One solution would be to set a message header to the eventType field, before sending the message, and then use:
#              spring.cloud.stream.rabbit.bindings.requestChannel.producer.routing-key-expression=headers.eventType.
              routing-key-expression: headers.type
          a-event-input:
            consumer:
#              binding-routing-key-delimiter: ','
              binding-routing-key: a
              declare-exchange: false
#              When true, consume from a queue with a name equal to the group.
#              Otherwise the queue name is destination.group. This is useful, for example, when using Spring Cloud Stream to consume from an existing RabbitMQ queue.
              queue-name-group-only: true
          b-event-input:
            consumer:
              binding-routing-key: b
              declare-exchange: false
              queue-name-group-only: true

      #          event-input:
#            consumer:
#              #requeue-rejected: true
#              auto-bind-dlq: true
#              republish-to-dlq: true
#              acknowledge-mode: MANUAL
#              prefetch: 3

#          aa-event:
#            producer:
#              exchangeType: direct
#            consumer:
#              exchangeType: direct
#      kafka:
#        binder:
#          brokers: 127.0.0.1:9092
#          zk-nodes: 127.0.0.1:2181
#          headers: eventType
      bindings:
        event-output:
          destination: service-output
        a-event-output:
          destination: a-output
#          content-type: application/json
#        event-input:
#          destination: service-event
#          group: ${spring.application.name}
#          consumer:
#            concurrency: 3
##            max-attempts: 4
        a-self-event-output:
          destination: a-input
        a-event-input:
          destination: service-output,a-output,a-input
          group: a-input
          consumer:
            concurrency: 3
#        b-event-input:
#          destination: service-output
#          group: b-input



#        event-bus-input-ext:
#          destination: institution-service-event
#          group: ${spring.application.name}
#          content-type: application/json

com:
  guns21:
    cloud:
      event:
        output:
#          patterns: '*'
        logging: false

#logging:
#  level:
#    root: DEBUG
#    org.springframework: info
#    com.guns21.cloud.event: debug
#  config: /Users/jliu/Develop/workspace/21guns/example/spring-stream-rabbitmq/src/main/resources/logback_admin.xml